// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCe3af5NL5T-1f5AkPh3H1mKSOlVtsUcx4',
    appId: '1:236338409913:web:18f864cf89fccbc2b78668',
    messagingSenderId: '236338409913',
    projectId: 'garden-guardian-7e377',
    authDomain: 'garden-guardian-7e377.firebaseapp.com',
    storageBucket: 'garden-guardian-7e377.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnbHROWeQ1aXpKQY2hmiIrhLO6vHH4X_o',
    appId: '1:236338409913:android:5f66c493306a9a49b78668',
    messagingSenderId: '236338409913',
    projectId: 'garden-guardian-7e377',
    storageBucket: 'garden-guardian-7e377.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCT1sWMgf6bTATy0FPBIIjx-2uKo1seN2o',
    appId: '1:236338409913:ios:3680ca8ce31d000eb78668',
    messagingSenderId: '236338409913',
    projectId: 'garden-guardian-7e377',
    storageBucket: 'garden-guardian-7e377.appspot.com',
    iosClientId: '236338409913-n49chvj5k6ne5vnkf6sda0gi8oh548ev.apps.googleusercontent.com',
    iosBundleId: 'com.example.gardenGuardian',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCT1sWMgf6bTATy0FPBIIjx-2uKo1seN2o',
    appId: '1:236338409913:ios:3680ca8ce31d000eb78668',
    messagingSenderId: '236338409913',
    projectId: 'garden-guardian-7e377',
    storageBucket: 'garden-guardian-7e377.appspot.com',
    iosClientId: '236338409913-n49chvj5k6ne5vnkf6sda0gi8oh548ev.apps.googleusercontent.com',
    iosBundleId: 'com.example.gardenGuardian',
  );
}
